### PR TITLE
MLIBZ-2852:Deprecate CACHE DataStore type

### PR DESCRIPTION
**Pull request by romanogolikhin**
#### Description
Since the CACHE DataStore will no longer be supported, the goal of this ticket is to place a deprecation notice in place for this type. 

#### Changes
Making the field "CACHE" as deprecated in  DataStoreType.cs.

#### Tests
No tests

### CODE REVIEW

**Comment by heyzooi** [comment]
@vinaygahlawat changing the default for `auto` will cause a big breaking change.
Maybe a better approach would be deprecate the method that assumes the `cache` as the default value and encourage users to migrate their code to use a overloading version of the method that specifically sets the store type desired instead of assume a default value of any kind.

**Comment by romanogolikhin** [comment]
@vinaygahlawat @heyzooi 
It seems to me Victor is right. If we change default type to AUTO, we will impact implicitly all code which uses default store type.

**Comment by vinaygahlawat** [comment]
@romanogolikhin yes I agree with @heyzooi. We discussed it, and both think the approach here should be to deprecate the constructor which has a default store type and suggest that developers use the constructor that specifically parameterizes the store type. Then after a few releases, we can remove the `CACHE` store and simultaneously change the default parameter for store type in the DataStore constructor to be `AUTO`.

**Comment by romanogolikhin** [comment]
@vinaygahlawat @heyzooi 
Ok. I will do it.

**Pull request merged**
