### PR TITLE
Lazy initialization of Cache and Queue

### PR DESCRIPTION
**Pull request by tejasranade**
#### Description
Avoids creation of the cache when using a network store

#### Changes
(incomplete)
Make the cache and queue creation methods in the DataStore lazy.

#### Tests
(incomplete)

### CODE REVIEW

**Comment by tejasranade** [comment]
@vinaygahlawat do we have a ticket that goes with this PR? Is this worth keeping open, or should we close?

**Comment by vinaygahlawat** [comment]
Yes, we have `MLIBZ-2458`, which is related to `MLIBZ-1339`, which I think is the original ticket that this fix was attempted for.

As for opening or closing this PR, I was keeping it open to see if there are parts of this that can be used when work on `MLIBZ-2458` starts next sprint, but we can close this out now without merging if you want. Either way is fine with me.

**Comment by tejasranade** [comment]
Ok. Closing this out. It'll still remain as reference, but we're basically saying we will end up redoing the changes anyway.

**Comment by vinaygahlawat** [comment]
Sounds good. I also closed out `MLIBZ-1339` as a duplicate of `MLIBZ-2458`.

**Pull request closed without merging**
